WITH CLIENTES1996AGO AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
   	WHERE OrderDate BETWEEN '1996-08-01' AND '1996-08-31'
),
CLIENTES1996SET AS
(
	SELECT DISTINCT(CustomerID)
   	FROM Orders
    	WHERE OrderDate BETWEEN '1996-09-01' AND '1996-09-30'
),
CLIENTES1996OUT AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
    	WHERE OrderDate BETWEEN '1996-10-01' AND '1996-10-31'
),
CLIENTES1996NOV AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
    	WHERE OrderDate BETWEEN '1996-11-01' AND '1996-11-30'
),
CLIENTES1996DEZ AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
   	WHERE OrderDate BETWEEN '1996-12-01' AND '1996-12-31'
),
CLIENTES1997JAN AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
    	WHERE OrderDate BETWEEN '1997-01-01' AND '1997-01-31'
),
CLIENTES1997FEV AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
    	WHERE OrderDate BETWEEN '1997-02-01' AND '1997-02-28'
),
CLIENTES1997MAR AS
(
	SELECT DISTINCT(CustomerID)
    	FROM Orders
    	WHERE OrderDate BETWEEN '1997-03-01' AND '1997-03-31'
),
baseAGO AS
(
	SELECT COUNT(DISTINCT CustomerID) AS M
    	FROM CLIENTES1996AGO
),
baseSET AS 
(
	SELECT COUNT(DISTINCT CustomerID) AS M
    	FROM CLIENTES1996SET
),
baseOUT AS 
(
	SELECT COUNT(DISTINCT CustomerID) AS M
    	FROM CLIENTES1996OUT
),
baseNOV AS 
(
	SELECT COUNT(DISTINCT CustomerID) AS M
    	FROM CLIENTES1996NOV
),
M1_AGO AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M1
    	FROM CLIENTES1996AGO A
    	INNER JOIN CLIENTES1996SET B ON A.CustomerID = B.CustomerID
),
M1_SET AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M1
    	FROM CLIENTES1996SET A
    	INNER JOIN CLIENTES1996OUT B ON A.CustomerID = B.CustomerID
),
M1_OUT AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M1
    	FROM CLIENTES1996OUT A
    	INNER JOIN CLIENTES1996NOV B ON A.CustomerID = B.CustomerID
),
M1_NOV AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M1
    	FROM CLIENTES1996NOV A
    	INNER JOIN CLIENTES1996DEZ B ON A.CustomerID = B.CustomerID
),
M2_AGO AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M2
    	FROM CLIENTES1996AGO A
    	INNER JOIN CLIENTES1996OUT B ON A.CustomerID = B.CustomerID
),
M2_SET AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M2
    	FROM CLIENTES1996SET A
    	INNER JOIN CLIENTES1996NOV B ON A.CustomerID = B.CustomerID
),
M2_OUT AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M2
    	FROM CLIENTES1996OUT A
    	INNER JOIN CLIENTES1996DEZ B ON A.CustomerID = B.CustomerID
),
M2_NOV AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M2
    	FROM CLIENTES1996NOV A
    	INNER JOIN CLIENTES1997JAN B ON A.CustomerID = B.CustomerID
),
M3_AGO AS 
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M3
    	FROM CLIENTES1996AGO A
    	INNER JOIN CLIENTES1996NOV B ON A.CustomerID = B.CustomerID
),
M3_SET AS 
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M3
    	FROM CLIENTES1996SET A
    	INNER JOIN CLIENTES1996DEZ B ON A.CustomerID = B.CustomerID
),
M3_OUT AS 
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M3
    	FROM CLIENTES1996OUT A
    	INNER JOIN CLIENTES1997JAN B ON A.CustomerID = B.CustomerID
),
M3_NOV AS 
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M3
    	FROM CLIENTES1996NOV A
    	INNER JOIN CLIENTES1997FEV B ON A.CustomerID = B.CustomerID
),
M4_AGO AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M4
    	FROM CLIENTES1996AGO A
    	INNER JOIN CLIENTES1996DEZ B ON A.CustomerID = B.CustomerID
),
M4_SET AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M4
    	FROM CLIENTES1996SET A
    	INNER JOIN CLIENTES1997JAN B ON A.CustomerID = B.CustomerID
),
M4_OUT AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M4
    	FROM CLIENTES1996OUT A
    	INNER JOIN CLIENTES1997FEV B ON A.CustomerID = B.CustomerID
),
M4_NOV AS
(
	SELECT COUNT(DISTINCT A.CustomerID) AS M4
    	FROM CLIENTES1996NOV A
    	INNER JOIN CLIENTES1997MAR B ON A.CustomerID = B.CustomerID
),
AGOSTO AS 
(
	SELECT *
	FROM baseAGO, M1_AGO, M2_AGO, M3_AGO, M4_AGO
),
SETEMBRO AS
(
	SELECT *
    	FROM baseSET, M1_SET, M2_SET, M3_SET, M4_SET 
),
OUTUBRO AS
(
	SELECT *
    	FROM baseOUT, M1_OUT, M2_OUT, M3_OUT, M4_OUT   
),
NOVEMBRO AS
(
	SELECT *
    	FROM baseNOV, M1_NOV, M2_NOV, M3_NOV, M4_NOV   
)

SELECT * -- Para printar a saída de cada consulta basta alterar o nome de AGOSTO para: (SETEMBRO, OUTUBRO ou NOVEMBRO) 
FROM AGOSTO

